// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk--MbZC5xgQpdgGqbeoHi4DwVqh5v52Q',
    appId: '1:487788205071:web:50bc025592fc8ca9d0ff7a',
    messagingSenderId: '487788205071',
    projectId: 'itable-93411',
    authDomain: 'itable-93411.firebaseapp.com',
    storageBucket: 'itable-93411.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGNjsmLpoLKO0J_ZdtBPgZXh5DgEeZBic',
    appId: '1:487788205071:android:8fc353ef3498e698d0ff7a',
    messagingSenderId: '487788205071',
    projectId: 'itable-93411',
    storageBucket: 'itable-93411.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoZx-U6KhdEZlIAzUQq5dIJy9rctdmrx0',
    appId: '1:487788205071:ios:7886f58702b8ad28d0ff7a',
    messagingSenderId: '487788205071',
    projectId: 'itable-93411',
    storageBucket: 'itable-93411.appspot.com',
    iosBundleId: 'com.itable.app.iTable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoZx-U6KhdEZlIAzUQq5dIJy9rctdmrx0',
    appId: '1:487788205071:ios:7886f58702b8ad28d0ff7a',
    messagingSenderId: '487788205071',
    projectId: 'itable-93411',
    storageBucket: 'itable-93411.appspot.com',
    iosBundleId: 'com.itable.app.iTable',
  );
}
